src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Subject", mappedBy="category")
     */
    private $subjects;

     /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subTitle;

    public function __construct()
    {
        $this->subjects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection|Subject[]
     */
    public function getSubjects(): Collection
    {
        return $this->subjects;
    }

    public function addSubject(Subject $subject): self
    {
        if (!$this->subjects->contains($subject)) {
            $this->subjects[] = $subject;
            $subject->setCategory($this);
        }

        return $this;
    }

    public function removeSubject(Subject $subject): self
    {
        if ($this->subjects->contains($subject)) {
            $this->subjects->removeElement($subject);
            // set the owning side to null (unless already changed)
            if ($subject->getCategory() === $this) {
                $subject->setCategory(null);
            }
        }

        return $this;
    }
    
    public function getSubTitle(): ?string
    {
        return $this->subTitle;
    }

    public function setSubTitle(string $subTitle): self
    {
        $this->subTitle = $subTitle;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title); 
    }
}

templates/pages/advantedResearch.twig
{% extends 'base.html.twig' %}

{% block title 'Portail documentaire - Accueil' %}

{% block body %}
	<div class="jumbotron text-center">
		<h1>Portail documentaire de la médiathèque du CND</h1>
		<p>
            Quanta autem vis amicitiae sit, ex hoc intellegi maxime potest, quod ex infinita societate generis humani, quam conciliavit ipsa natura, ita contracta res est et adducta in angustum ut omnis caritas aut inter duos aut inter paucos iungeretur.
        </p>
	</div>
	<div class="container">
			{{ form_start(form) }}
			<div class="form-row align-items-end">
				<div class="col">
					{{ form_row(form.titre) }}
				</div>
				<div class="col">
					{{ form_row(form.auteur) }}
				</div>
				<div class="col">
					{{ form_row(form.type) }}
				</div>
				
				<div class="col">
					{{ form_row(form.persons) }}
				</div>
			</div>
			<div class="form-row align-items-end">
				<div class="col">
					{{ form_row(form.texte) }}
				</div>
			</div>
			<div class="form-row align-items-end">
				<div class="col">
					<!--  class form-group aligne le bouton  -->
					<div class="form-group">
						<button class="btn btn-primary">Rechercher</button>
					</div>
				</div>
			</div>
	   {{ form_end(form) }}
<div class="container mt-4">
		{# display navigation #}
		<div class="navigation">
			{{ knp_pagination_render(resources) }}
		</div>
	<h2>Les dernières ressources</h2>
	<div class="row">
		{% for resource in resources %}
			<div class="col-md-4">
				{% include '/resource/_resource.html.twig' %}
			</div>
		{% endfor %}
	</div>
	</div>
	{# display navigation #}
	<div class="navigation">
		{{ knp_pagination_render(resources) }}
	</div>
</div>

{% endblock %}

templates/pages/collection.html.twig
{% extends 'base-frontoffice.html.twig' %}
{% block title 'Portail documentaire - collection' %}
{% block body %}			
				<!-- Six -->
				<section class="wrapper style1 align-center">
					<div class="inner">
						<h2>{{ collection.title }}</h2>
						{{ collection.description|raw }}
				</section>
				<section>
				 	<div class="row">
						{% for subject in collection.subjects %}
						<!-- { set resource = resource.transformed } -->
						{% include '/subject/_subject.html.twig' %}
						{% endfor %}
					</div>
				<!-- Seven -->
				<section class="wrapper style1 align-center">
						<div class="inner medium">
							<h2>Vous avez une question</h2>
							<form method="post" action="#">
								<div class="fields">
									<div class="field half">
										<label for="name">Nom</label>
										<input type="text" name="name" id="name" value="" />
									</div>
									<div class="field half">
										<label for="email">Email</label>
										<input type="email" name="email" id="email" value="" />
									</div>
									<div class="field">
										<label for="message">Message</label>
										<textarea name="message" id="message" rows="6"></textarea>
									</div>
								</div>
								<ul class="actions special">
									<li><input type="submit" name="submit" id="submit" value="Envoyer" /></li>
								</ul>
							</form>

						</div>
				</section>
{% endblock %}
				

templates/pages/home.html_o.twig
{% extends 'base-frontoffice.html.twig' %}

{% block title 'Portail documentaire - Accueil' %}

{% block body %}
	<div class="jumbotron text-center">
		<h1>Portail documentaire de la médiathèque du CND</h1>
		<p>
            Quanta autem vis amicitiae sit, ex hoc intellegi maxime potest, quod ex infinita societate generis humani, quam conciliavit ipsa natura, ita contracta res est et adducta in angustum ut omnis caritas aut inter duos aut inter paucos iungeretur.
        </p>
	</div>
	<div class="container">
		<form method="get" action="{{ path('resources.search') }}">
			<div class="form-group">
				<input class="form-control"
					type="text"
					name="q"
					id="search-input"
					suggest="{{ path('resources.fullsearch') }}"
					placeholder="Saisir votre recherche">
			</div>
			<button class="btn btn-primary">Rechercher</button>
		</form>
		
<div class="container mt-4">
	{# display navigation #}
		
		<h2>Les dernières ressources</h2>
		<div class="row">
			{% for resource in resources %}
				<div class="col-md-4">
					{% include '/resource/_resource.html.twig' %}
				</div>
			{% endfor %}
		</div>
		</div>
	
</div>

{% endblock %}

templates/pages/results.html.twig
{% extends 'base-frontoffice.html.twig' %}
{% block title 'Portail documentaire - Résultats' %}
{% block body %}			
				<!-- Six -->
					<section>
						<div class="container">
						<div class="row" style="width:100%;">
							<div class="col-6 col-md-3">
								<h3 class="">Filtres</h3>
								<h5 class="facets-title"><button type="button" class="btn btn-outline-secondary">Types de documents</button></h5>
								<ul class="list-group">
									{% for type in typesFacet.buckets %}
										<li class="list-group-item d-flex justify-content-between align-items-center">
											<a href="/searchfacet?q={{app.session.get('q') ~ ' ' ~ type.key }}&fields=_all">{{ type.key|upper }}</a>
								    		<span class="badge badge-primary badge-pill">{{ type.doc_count }}</span>
								 		</li>
									{% endfor %}
								</ul>
								<h5 class="facets-title"><button type="button" class="btn btn-outline-secondary">Mots clés</button></h5>
								<ul class="list-group">
									{% for tag in tagsFacet.buckets %}
										<li class="list-group-item d-flex justify-content-between align-items-center">
											<a href="/searchfacet?q={{app.session.get('q') ~ ' ' ~ tag.key }}&fields=_all">{{ tag.key|upper }}</a>
							   				<span class="badge badge-primary badge-pill">{{ tag.doc_count }}</span>
							 			</li>
									{% endfor %}
							</ul>
								<h5 class="facets-title"><button type="button" class="btn btn-outline-secondary">Personnes</button></h5>
								<ul class="list-group">
									{% for person in personsFacet.buckets %}
										<li class="list-group-item d-flex justify-content-between align-items-center">
											<a href="/searchfacet?q={{app.session.get('q') ~ ' ' ~ person.key }}&fields=_all">{{ person.key|upper }}</a>
								   			<span class="badge badge-primary badge-pill">{{ person.doc_count }}</span>
								 		</li>
									{% endfor %}
								</ul>
								<h5 class="facets-title"><button type="button" class="btn btn-outline-secondary">Oeuvres</button></h5>
								<ul class="list-group">
									{% for oeuvre in oeuvresFacet.buckets %}
										<li class="list-group-item d-flex justify-content-between align-items-center">
											<a href="/searchfacet?q={{app.session.get('q') ~ ' ' ~ oeuvre.key }}&fields=_all">{{ oeuvre.key|upper }}</a>
								   			<span class="badge badge-primary badge-pill">{{ oeuvre.doc_count }}</span>
								 		</li>
									{% endfor %}
								</ul>
								<h5 class="facets-title"><button type="button" class="btn btn-outline-secondary">Structures</button></h5>
								<ul class="list-group">
									{% for organisme in organismesFacet.buckets %}
										<li class="list-group-item d-flex justify-content-between align-items-center">
											<a href="/searchfacet?q={{app.session.get('q') ~ ' ' ~ organisme.key }}&fields=_all">{{ organisme.key|upper }}</a>
								   			<span class="badge badge-primary badge-pill">{{ organisme.doc_count }}</span>
								 		</li>
									{% endfor %}
								</ul>
							</ul>
						 </div>
						<div class="col-12 col-md-9">
							<div class="row">
								<div class="col">
									<h3 class="">Nombre de ressources : {{ ' ' ~ nbresult }}</h3>
								</div>
							</div>
							<div class="row width-card">
								{% for resource in pagination %}
								{% set resource = resource.transformed %}
								{% include '/resource/_resource.html.twig' %}
								{% endfor %}
							</div>
							<div class="row width-card">
								<div class="col">
									{% block pagination %}
										{% if pagination.haveToPaginate %}
											{{ pagerfanta(pagination, 'twitter_bootstrap4', {prev_message: '← Précédent', next_message: 'Suivant →'}) }}
										{% endif %}
									{% endblock %}
								</div>
							</div>
						</div>
					</div>
				</div>
					
				</section>
				<!-- Seven -->
				<section class="wrapper style1 align-center">
						<div class="inner medium">
							<h2>Vous avez une question</h2>
							<form method="post" action="#">
								<div class="fields">
									<div class="field half">
										<label for="name">Nom</label>
										<input type="text" name="name" id="name" value="" />
									</div>
									<div class="field half">
										<label for="email">Email</label>
										<input type="email" name="email" id="email" value="" />
									</div>
									<div class="field">
										<label for="message">Message</label>
										<textarea name="message" id="message" rows="6"></textarea>
									</div>
								</div>
								<ul class="actions special">
									<li><input type="submit" name="submit" id="submit" value="Envoyer" /></li>
								</ul>
							</form>

						</div>
				</section>
{% endblock %}
				

templates/pages/results.html_o.twig
{% extends 'base.html.twig' %}
{% block title 'Portail documentaire - Résultats' %}
{% block body %}
	<div class="jumbotron text-center">
		<h1>Portail documentaire de la médiathèque du CND</h1>
		<p>
            Quanta autem vis amicitiae sit, ex hoc intellegi maxime potest, quod ex infinita societate generis humani, quam conciliavit ipsa natura, ita contracta res est et adducta in angustum ut omnis caritas aut inter duos aut inter paucos iungeretur.
        </p>
	</div>
	<div class="container">
		<form method="get" action="{{ path('resources.search') }}">
			<div class="form-group">
				<input class="form-control"
					type="text"
					name="q"
					id="search-input"
					data-suggest="{{ path('resources.fullsearch') }}"
					placeholder="Saisir votre recherche">
			</div>
			<button class="btn btn-primary">Rechercher</button>
		</form>
<div class="container mt-4">
	{# display navigation #}
		<h3>Nombre de ressources : {{ nbresult }}</h3>

		<div class="row">
			{% for resource in pagination %}
			{% set resource = resource.transformed %}
				<div class="col-md-4">
					{% include '/resource/_resource.html.twig' %}
				</div>
			{% endfor %}
		</div>
		</div>
			{% block pagination %}
				{% if pagination.haveToPaginate %}
					{{ pagerfanta(pagination, 'twitter_bootstrap4', {prev_message: '← Précédent', next_message: 'Suivant →'}) }}
				{% endif %}
			{% endblock %}
</div>

{% endblock %}

templates/pages/results_tests.html.twig
{% extends 'base-frontoffice.html.twig' %}
{% block title 'Portail documentaire - Résultats' %}
{% block body %}			
				<!-- Six -->
					<section>
						<h3 class="nb-resultats">Nombre de ressources : {{ nbresult }}</h3>
						<div class="row">
							{% for resource in results %}
							{% set resource = resource.transformed %}
							{% include '/resource/_resource.html.twig' %}
							{% endfor %}
						</div>
						<div class="row">
							<div class="col">
{% block pagination %}
	
			{{ pagerfanta(results, 'twitter_bootstrap4', {prev_message: '← Précédent', next_message: 'Suivant →'}) }}
	
{% endblock %}
							</div>
						</div>

					</section>
				<!-- Seven -->
					<section class="wrapper style1 align-center">
						<div class="inner medium">
							<h2>Vous avez une question</h2>
							<form method="post" action="#">
								<div class="fields">
									<div class="field half">
										<label for="name">Nom</label>
										<input type="text" name="name" id="name" value="" />
									</div>
									<div class="field half">
										<label for="email">Email</label>
										<input type="email" name="email" id="email" value="" />
									</div>
									<div class="field">
										<label for="message">Message</label>
										<textarea name="message" id="message" rows="6"></textarea>
									</div>
								</div>
								<ul class="actions special">
									<li><input type="submit" name="submit" id="submit" value="Envoyer" /></li>
								</ul>
							</form>

						</div>
					</section>
{% endblock %}
				

templates/pages/subject.html.twig
{% extends 'base-frontoffice.html.twig' %}
{% block title 'Portail documentaire - collection' %}
{% block body %}			
				<!-- Six -->
				<section class="wrapper style1 align-center">
					<div class="inner">
						<h2>{{ subject.category.title }}</h2>
						<h2>{{ subject.title }}</h2>
						<h3>{{ subject.subTitle }}</h3>
						{{ subject.description|raw }}
				</section>
				<section>
				 	<div class="row">
						{% for resource in subject.resources %}
							<!-- { set resource = resource.transformed } -->
							{% include '/resource/_resource.html.twig' %}
						{% endfor %}
					</div>
				<!-- Seven -->
				<section class="wrapper style1 align-center">
						<div class="inner medium">
							<h2>Vous avez une question</h2>
							<form method="post" action="#">
								<div class="fields">
									<div class="field half">
										<label for="name">Nom</label>
										<input type="text" name="name" id="name" value="" />
									</div>
									<div class="field half">
										<label for="email">Email</label>
										<input type="email" name="email" id="email" value="" />
									</div>
									<div class="field">
										<label for="message">Message</label>
										<textarea name="message" id="message" rows="6"></textarea>
									</div>
								</div>
								<ul class="actions special">
									<li><input type="submit" name="submit" id="submit" value="Envoyer" /></li>
								</ul>
							</form>

						</div>
				</section>
{% endblock %}
				